const cards = [
  {
    id: 1,
    name: "Aethron",
    title: "The Time Paradox",
    type: "Hero",
    rarity: "Legendary",
    image: "/assets/cards/aethron.jpeg",
    stats: {
      STR: 86,
      AGI: 102,
      VIT: 95,
      INT: 107,
      PWR: 100,
      TOT: 490,
    },
  },
  {
    id: 2,
    name: "Dissona",
    title: "The Frequency Breaker",
    type: "Villain",
    rarity: "Legendary",
    image: "/assets/cards/dissona.jpeg",
    stats: {
      STR: 78,
      AGI: 96,
      VIT: 84,
      INT: 103,
      PWR: 109,
      TOT: 470,
    },
  },
  {
    id: 3,
    name: "Elyndra",
    title: "The Lifeforge",
    type: "Hero",
    rarity: "Legendary",
    image: "/assets/cards/elyndra.jpeg",
    stats: {
      STR: 86,
      AGI: 80,
      VIT: 104,
      INT: 94,
      PWR: 98,
      TOT: 462,
    },
  },
  {
    id: 4,
    name: "Kryon",
    title: "The Neural Strike",
    type: "Hero",
    rarity: "Apex",
    image: "/assets/cards/kryon.jpeg",
    stats: {
      STR: 93,
      AGI: 101,
      VIT: 88,
      INT: 107,
      PWR: 90,
      TOT: 479,
    },
  },
  {
    id: 5,
    name: "Malgrave",
    title: "The Iron Executor",
    type: "Villain",
    rarity: "Apex",
    image: "/assets/cards/malgrave.jpeg",
    stats: {
      STR: 92,
      AGI: 72,
      VIT: 109,
      INT: 90,
      PWR: 104,
      TOT: 467,
    },
  },
  {
    id: 6,
    name: "Nyxara",
    title: "The Mind Veil",
    type: "Villain",
    rarity: "Apex",
    image: "/assets/cards/nyxara.jpeg",
    stats: {
      STR: 93,
      AGI: 95,
      VIT: 89,
      INT: 108,
      PWR: 102,
      TOT: 487,
    },
  },
  {
    id: 7,
    name: "Rakthar",
    title: "The Warfang",
    type: "Hero",
    rarity: "Apex",
    image: "/assets/cards/rakthar.jpeg",
    stats: {
      STR: 99,
      AGI: 87,
      VIT: 94,
      INT: 76,
      PWR: 82,
      TOT: 438,
    },
  },
  {
    id: 8,
    name: "Seraphyx",
    title: "The Sky Lance",
    type: "Hero",
    rarity: "Mythic",
    image: "/assets/cards/seraphyx.jpeg",
    stats: {
      STR: 106,
      AGI: 91,
      VIT: 96,
      INT: 88,
      PWR: 104,
      TOT: 485,
    },
  },
  {
    id: 9,
    name: "Thalvor",
    title: "The Abyss Throne",
    type: "Villain",
    rarity: "Titan",
    image: "/assets/cards/thalvor.jpeg",
    stats: {
      STR: 96,
      AGI: 70,
      VIT: 101,
      INT: 89,
      PWR: 104,
      TOT: 460,
    },
  },
  {
    id: 10,
    name: "Velkaris",
    title: "The Night Cut",
    type: "Villain",
    rarity: "Apex",
    image: "/assets/cards/velkaris.jpeg",
    stats: {
      STR: 99,
      AGI: 105,
      VIT: 82,
      INT: 87,
      PWR: 91,
      TOT: 464,
    },
  },
  {
    id: 11,
    name: "Voraxis",
    title: "The Chaos Splinter",
    type: "Villain",
    rarity: "Titan",
    image: "/assets/cards/voraxis.jpeg",
    stats: {
      STR: 100,
      AGI: 68,
      VIT: 92,
      INT: 95,
      PWR: 104,
      TOT: 459,
    },
  },
  {
    id: 12,
    name: "Xekroth",
    title: "The Biophage",
    type: "Villain",
    rarity: "Legendary",
    image: "/assets/cards/xekroth.jpeg",
    stats: {
      STR: 93,
      AGI: 74,
      VIT: 97,
      INT: 101,
      PWR: 109,
      TOT: 474,
    },
  },
];
